### ISSUE TITLE
github版のチケット機能issueを試してみよう～

### ISSUE THREAD

**Issue by MarieTest** [nikkitest/Test#1]
どの程度の機能を持っているのか
使いやすいか
チェック @norikoji

**Comment by norikoji** [comment]
これどうすれば良いの？

**Comment by MarieTest** [comment]
#2 
このissueは上記の↑プルリクエストと関連づけてみます。小島さんにプルリクエストの内容をレビューしてもらった後、プルリクエストのページから”マージ”を選んでクリックし、マージ完了後にissueもcloseというような感じでどうでしょうか。。

**Comment by norikoji** [comment]
とりあえずプルしたのでクローズしまーす。
